export const CRON_EXPRESSION = Symbol("CRON_EXPRESSION");
export const CRON_OPTIONS = Symbol("CRON_OPTIONS");
export const CRON_MODULE_REDIS_OPTIONS = Symbol("CRON_MODULE_REDIS_OPTIONS");
export const CRON_MODULE_ON_QUEUE_HOOK = Symbol("CRON_MODULE_ON_QUEUE_HOOK");
